# Modbus TCP Server Configuration for SimpleThermalMVP

# Server settings
port = 5502
update_interval_ms = 100  # 10 Hz simulation rate

# Register mapping - using standard Modbus addressing
[registers]
# Use offset 0 for registers (protocol addressing)
# OpenPLC %IW100 = register 100 = address 100 in protocol
temperature_address = 100     # Was 40001, now 100 (OpenPLC %IW100)
heater_state_address = 101    # Was 40002, now 101 (OpenPLC %IW101)

# Note: Coil 0 still controls heater (standard coil addressing)